# Generated by Django 4.2.23 on 2026-07-11 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("risk", "Risk Management"),
                            ("compliance", "Compliance"),
                            ("vendor", "Vendor Management"),
                            ("policy", "Policy Management"),
                            ("training", "Training & Awareness"),
                            ("integrated", "Integrated Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_name", models.CharField(max_length=255)),
                ("metric_key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("calculation_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("data_source", models.CharField(max_length=255)),
                ("calculation_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("data_freshness", models.DateTimeField(blank=True, null=True)),
                ("is_cached", models.BooleanField(default=True)),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_metrics",
                "ordering": ["-calculation_date"],
                "indexes": [
                    models.Index(
                        fields=["category", "metric_key"], name="analytics_m_categor_9d59b8_idx"
                    ),
                    models.Index(
                        fields=["calculation_date"], name="analytics_m_calcula_6b4077_idx"
                    ),
                    models.Index(
                        fields=["cache_expires_at"], name="analytics_m_cache_e_39f17d_idx"
                    ),
                ],
                "unique_together": {("metric_key", "calculation_date")},
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Report"),
                            ("compliance", "Compliance Report"),
                            ("risk", "Risk Assessment Report"),
                            ("vendor", "Vendor Risk Report"),
                            ("audit", "Audit Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sections", models.JSONField(default=list)),
                ("default_filters", models.JSONField(default=dict)),
                ("styling_config", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True, related_name="accessible_templates", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"], name="report_temp_created_28b062_idx"
                    ),
                    models.Index(fields=["template_type"], name="report_temp_templat_fe87ac_idx"),
                    models.Index(fields=["is_public"], name="report_temp_is_publ_3f1784_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Dashboard"),
                            ("operational", "Operational Dashboard"),
                            ("compliance", "Compliance Dashboard"),
                            ("risk", "Risk Dashboard"),
                            ("vendor", "Vendor Dashboard"),
                            ("policy", "Policy Dashboard"),
                            ("training", "Training Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("layout_config", models.JSONField(blank=True, default=dict)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("refresh_interval", models.PositiveIntegerField(default=300)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_with_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboard_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_configurations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "dashboard_type"], name="dashboard_c_user_id_71bdae_idx"
                    ),
                    models.Index(fields=["is_shared"], name="dashboard_c_is_shar_893205_idx"),
                ],
                "unique_together": {("user", "dashboard_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Dashboard"),
                            ("compliance", "Compliance Analytics"),
                            ("risk", "Risk Management"),
                            ("vendor", "Vendor Risk Assessment"),
                            ("policy", "Policy Management"),
                            ("training", "Training Effectiveness"),
                            ("integrated", "Integrated Risk Posture"),
                            ("operational", "Operational Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Report"),
                            ("excel", "Excel Spreadsheet"),
                            ("csv", "CSV Data Export"),
                            ("json", "JSON Data Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_range_start", models.DateField(blank=True, null=True)),
                ("date_range_end", models.DateField(blank=True, null=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("generation_time_seconds", models.FloatField(blank=True, null=True)),
                ("data_points_included", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-created_at"],
                        name="analytics_r_request_a140a8_idx",
                    ),
                    models.Index(fields=["status"], name="analytics_r_status_4dcdd6_idx"),
                    models.Index(fields=["report_type"], name="analytics_r_report__21878c_idx"),
                    models.Index(fields=["expires_at"], name="analytics_r_expires_a9ce7d_idx"),
                ],
            },
        ),
    ]
