version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "donolu"  # Replace with actual GitHub usernames
    assignees:
      - "donolu"  # Replace with actual GitHub usernames
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
      - dependency-name: "djangorestframework"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly" 
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "donolu"
    assignees:
      - "donolu"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "frontend"
      - "nodejs"
    ignore:
      # Ignore major React updates until ready
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "donolu"
    assignees:
      - "donolu"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "donolu"
    assignees:
      - "donolu"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"