[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
    # directories
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | \.pytest_cache
  | migrations
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
known_django = "django"
known_first_party = ["app", "core", "authn", "billing", "catalogs", "compliance", "risk", "vendors", "policies", "training", "vuln", "events", "audit", "exports", "search", "api"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["migrations", "venv", ".venv", "node_modules"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings.test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = ["app"]
addopts = """
    --verbose
    --tb=short
    --strict-markers
    --strict-config
    --reuse-db
    --nomigrations
    --cov=app
    --cov-report=html
    --cov-report=term-missing
    --cov-fail-under=70
"""
filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango50Warning",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
    "stripe: marks tests that require Stripe API",
    "azure: marks tests that require Azure services",
]

[tool.coverage.run]
source = "."
omit = [
    "*/migrations/*",
    "*/venv/*",
    "*/node_modules/*",
    "manage.py",
    "*/settings/*",
    "*/tests/*",
    "*/__pycache__/*",
    "*/staticfiles/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.bandit]
exclude_dirs = ["tests", "migrations", "node_modules", "venv"]
skips = ["B101", "B601"]  # Skip assert_used_in_tests, shell_injection_process

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true