# Generated by Django 5.0.6 on 2025-08-25 15:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Risk Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(help_text='Unique risk identifier', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact', models.PositiveIntegerField(help_text='Impact level (1=Very Low, 5=Very High)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('likelihood', models.PositiveIntegerField(help_text='Likelihood level (1=Very Low, 5=Very High)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Calculated risk level', max_length=20)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessed', 'Assessed'), ('treatment_planned', 'Treatment Planned'), ('treatment_in_progress', 'Treatment in Progress'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('transferred', 'Transferred'), ('closed', 'Closed')], default='identified', max_length=30)),
                ('treatment_strategy', models.CharField(blank=True, choices=[('mitigate', 'Mitigate'), ('accept', 'Accept'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], max_length=20)),
                ('treatment_description', models.TextField(blank=True, help_text='Description of the treatment approach')),
                ('identified_date', models.DateField(default=django.utils.timezone.now)),
                ('last_assessed_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('potential_impact_description', models.TextField(blank=True, help_text='Detailed description of potential impact')),
                ('current_controls', models.TextField(blank=True, help_text='Existing controls or mitigations in place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('risk_owner', models.ForeignKey(blank=True, help_text='Person responsible for managing this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risk.riskcategory')),
            ],
            options={
                'ordering': ['-risk_level', '-impact', '-likelihood', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RiskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(help_text='Unique action identifier', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('preventive', 'Preventive Control'), ('detective', 'Detective Control'), ('corrective', 'Corrective Action'), ('policy', 'Policy/Procedure'), ('training', 'Training/Awareness'), ('technical', 'Technical Implementation'), ('assessment', 'Assessment/Review'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(help_text='Date when this action must be completed')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost to complete this action', max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost incurred for this action', max_digits=10, null=True)),
                ('estimated_effort_hours', models.PositiveIntegerField(blank=True, help_text='Estimated effort in hours', null=True)),
                ('success_criteria', models.TextField(blank=True, help_text='Specific criteria that define successful completion')),
                ('dependencies', models.TextField(blank=True, help_text='Dependencies or prerequisites for this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person responsible for completing this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risk_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risk_actions', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='risk.risk')),
            ],
            options={
                'ordering': ['due_date', '-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RiskActionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('document', 'Document/Policy'), ('screenshot', 'Screenshot'), ('report', 'Report/Analysis'), ('certificate', 'Certificate'), ('configuration', 'Configuration File'), ('training_record', 'Training Record'), ('audit_log', 'Audit Log'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='risk_action_evidence/')),
                ('external_link', models.URLField(blank=True, help_text='Link to external evidence or system')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('evidence_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='risk.riskaction')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_risk_action_evidence', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_risk_action_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evidence_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskActionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('progress', 'Progress Update'), ('issue', 'Issue/Blocker'), ('completion', 'Completion'), ('status_change', 'Status Change'), ('general', 'General')], default='progress', max_length=30)),
                ('progress_percentage', models.PositiveIntegerField(blank=True, help_text='Progress percentage at time of note', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='risk.riskaction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_action_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskActionReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reminders', models.BooleanField(default=True, help_text='Whether to send automated reminders to this user')),
                ('advance_warning_days', models.PositiveIntegerField(default=7, help_text='Days before due date to send advance warning')),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='daily', help_text='How frequently to send reminders', max_length=10)),
                ('custom_reminder_days', models.JSONField(blank=True, default=list, help_text="Custom reminder days pattern [1, 3, 7, 14] - only used when frequency is 'custom'")),
                ('email_notifications', models.BooleanField(default=True, help_text='Send email notifications')),
                ('overdue_reminders', models.BooleanField(default=True, help_text='Send reminders for overdue actions')),
                ('weekly_digest_enabled', models.BooleanField(default=True, help_text='Send weekly summary digest')),
                ('weekly_digest_day', models.PositiveIntegerField(default=1, help_text='Day of week for digest (0=Monday, 6=Sunday)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('silence_completed', models.BooleanField(default=True, help_text='Stop sending reminders for completed actions')),
                ('silence_cancelled', models.BooleanField(default=True, help_text='Stop sending reminders for cancelled actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User for whom risk action reminders are configured', on_delete=django.db.models.deletion.CASCADE, related_name='risk_action_reminder_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Action Reminder Configuration',
                'verbose_name_plural': 'Risk Action Reminder Configurations',
            },
        ),
        migrations.CreateModel(
            name='RiskActionReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('advance_warning', 'Advance Warning'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('weekly_digest', 'Weekly Digest'), ('assignment', 'Assignment Notification')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=300)),
                ('email_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('days_before_due', models.IntegerField(blank=True, help_text='Days before due date when sent (negative for overdue)', null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='risk.riskaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_action_reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('impact_levels', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)])),
                ('likelihood_levels', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)])),
                ('matrix_config', models.JSONField(default=dict, help_text='Matrix configuration mapping impact x likelihood to risk levels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risk_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Risk Matrices',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.riskmatrix'),
        ),
        migrations.CreateModel(
            name='RiskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('assessment', 'Assessment'), ('treatment', 'Treatment'), ('review', 'Review'), ('status_change', 'Status Change')], default='general', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_notes', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='risk.risk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskaction',
            index=models.Index(fields=['status', 'due_date'], name='risk_riskac_status_90a0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskaction',
            index=models.Index(fields=['assigned_to', 'status'], name='risk_riskac_assigne_cb1cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='riskaction',
            index=models.Index(fields=['risk', 'status'], name='risk_riskac_risk_id_f87612_idx'),
        ),
        migrations.AddIndex(
            model_name='riskaction',
            index=models.Index(fields=['due_date'], name='risk_riskac_due_dat_4af23a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskaction',
            index=models.Index(fields=['priority', 'status'], name='risk_riskac_priorit_4ec824_idx'),
        ),
        migrations.AddIndex(
            model_name='riskactionevidence',
            index=models.Index(fields=['action', '-evidence_date'], name='risk_riskac_action__aa84f6_idx'),
        ),
        migrations.AddIndex(
            model_name='riskactionevidence',
            index=models.Index(fields=['evidence_type'], name='risk_riskac_evidenc_06979f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskactionevidence',
            index=models.Index(fields=['is_validated'], name='risk_riskac_is_vali_e0a97a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskactionreminderlog',
            index=models.Index(fields=['action', 'user', 'reminder_type'], name='risk_riskac_action__705fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='riskactionreminderlog',
            index=models.Index(fields=['sent_at'], name='risk_riskac_sent_at_e5b20a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskactionreminderlog',
            unique_together={('action', 'user', 'reminder_type', 'days_before_due')},
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['status', 'risk_level'], name='risk_risk_status_51fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_owner', 'status'], name='risk_risk_risk_ow_be9206_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['next_review_date'], name='risk_risk_next_re_e70914_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['category', 'risk_level'], name='risk_risk_categor_75ecb9_idx'),
        ),
    ]
