# Generated by Django 5.2.15 on 2026-07-16 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskactionevidence",
            name="evidence_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
