# Generated by Django 5.2.15 on 2026-07-15 20:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("risk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("web", "Web application"),
                            ("host", "Host"),
                            ("api", "API endpoint"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending_approval",
                        max_length=30,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scan_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_scan_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScanSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scan_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="vuln.scantarget",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScanJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scanner",
                    models.CharField(
                        choices=[("nuclei", "Nuclei")], default="nuclei", max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("findings_count", models.PositiveIntegerField(default=0)),
                ("scan_config", models.JSONField(blank=True, default=dict)),
                ("raw_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_scan_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_jobs",
                        to="vuln.scanschedule",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_jobs",
                        to="vuln.scantarget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("scanner_name", models.CharField(default="nuclei", max_length=50)),
                ("scanner_finding_id", models.CharField(blank=True, max_length=255)),
                ("template_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                ("matched_at", models.CharField(blank=True, max_length=500)),
                ("cve", models.CharField(blank=True, max_length=80)),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted_risk", "Accepted risk"),
                            ("remediated", "Remediated"),
                            ("false_positive", "False positive"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="vuln.scanjob",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vulnerability_findings",
                        to="risk.risk",
                    ),
                ),
                (
                    "risk_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vulnerability_findings",
                        to="risk.riskaction",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="vuln.scantarget",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "-last_seen_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scantarget",
            index=models.Index(
                fields=["status", "target_type"], name="vuln_scanta_status_545fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scantarget",
            index=models.Index(fields=["owner"], name="vuln_scanta_owner_i_53d8ce_idx"),
        ),
        migrations.AddIndex(
            model_name="scantarget",
            index=models.Index(
                fields=["address"], name="vuln_scanta_address_41b591_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanschedule",
            index=models.Index(
                fields=["target", "is_active"], name="vuln_scansc_target__b82129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanschedule",
            index=models.Index(
                fields=["next_run_at", "is_active"],
                name="vuln_scansc_next_ru_253380_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["target", "status"], name="vuln_scanjo_target__ea9cfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["status", "created_at"], name="vuln_scanjo_status_6041c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityfinding",
            index=models.Index(
                fields=["target", "status"], name="vuln_vulner_target__384102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityfinding",
            index=models.Index(
                fields=["severity", "status"], name="vuln_vulner_severit_272d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityfinding",
            index=models.Index(
                fields=["scanner_finding_id"], name="vuln_vulner_scanner_5df45e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityfinding",
            index=models.Index(
                fields=["last_seen_at"], name="vuln_vulner_last_se_b44384_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilityfinding",
            unique_together={("target", "fingerprint")},
        ),
    ]
