# Generated by Django 5.1.4 on 2025-08-22 manually created

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_alter_controlassessment_implementation_status'),
        ('core', '0002_document_documentaccess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('assessment_summary', 'Assessment Summary Report'), ('detailed_assessment', 'Detailed Assessment Report'), ('evidence_portfolio', 'Evidence Portfolio Report'), ('compliance_gap', 'Compliance Gap Analysis')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('include_evidence_summary', models.BooleanField(default=True)),
                ('include_implementation_notes', models.BooleanField(default=True)),
                ('include_overdue_items', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('assessments', models.ManyToManyField(blank=True, help_text='Specific assessments to include (if applicable)', to='catalogs.controlassessment')),
                ('framework', models.ForeignKey(blank=True, help_text='Framework to generate report for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.framework')),
                ('generated_file', models.ForeignKey(blank=True, help_text='Generated PDF report file', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentreport',
            index=models.Index(fields=['requested_by', '-requested_at'], name='exports_ass_request_a28c93_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentreport',
            index=models.Index(fields=['status'], name='exports_ass_status_fac2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentreport',
            index=models.Index(fields=['report_type'], name='exports_ass_report__17aaeb_idx'),
        ),
    ]