# Generated by Django 5.2.15 on 2026-07-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_plan_included_modules_subscription_enabled_modules_and_more"),
        ("exports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Tenant data export", max_length=200),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("xlsx", "Excel workbook"),
                            ("csv_zip", "CSV archive"),
                        ],
                        default="xlsx",
                        max_length=20,
                    ),
                ),
                ("selected_modules", models.JSONField(blank=True, default=list)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Generation"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("generation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("record_counts", models.JSONField(blank=True, default=dict)),
                ("coverage_manifest", models.JSONField(blank=True, default=list)),
                (
                    "generated_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated spreadsheet or CSV archive",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_data_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-requested_at"],
                        name="exports_ten_request_645331_idx",
                    ),
                    models.Index(
                        fields=["status"], name="exports_ten_status_4ccd5c_idx"
                    ),
                    models.Index(
                        fields=["export_format"], name="exports_ten_export__a03306_idx"
                    ),
                ],
            },
        ),
    ]
