# Generated by Django 5.2.15 on 2026-07-15 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0003_templatedocument"),
        ("core", "0002_plan_included_modules_subscription_enabled_modules_and_more"),
        ("risk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceArtefact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artefact_id", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "artefact_type",
                    models.CharField(
                        choices=[
                            ("scope_document", "Scope Document"),
                            ("metrics_pack", "Metrics Pack"),
                            ("agenda", "Agenda"),
                            ("management_review_pack", "Management Review Pack"),
                            (
                                "regulatory_contractual_sheet",
                                "Regulatory and Contractual Sheet",
                            ),
                            ("nonconformity_log", "Non-Conformity Log"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=30)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("review_due_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_governance_artefacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="governance_artefacts",
                        to="catalogs.control",
                    ),
                ),
                (
                    "linked_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="governance_artefacts",
                        to="core.document",
                    ),
                ),
                (
                    "linked_frameworks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="governance_artefacts",
                        to="catalogs.framework",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_governance_artefacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_artefacts",
                        to="catalogs.templatedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["artefact_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_id", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("regulation", "Regulation"),
                            ("contract", "Contract"),
                            ("standard", "Standard"),
                            ("policy", "Policy"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issuing_body", models.CharField(blank=True, max_length=255)),
                ("jurisdiction", models.CharField(blank=True, max_length=120)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "applicability_status",
                    models.CharField(
                        choices=[
                            ("under_review", "Under Review"),
                            ("applicable", "Applicable"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="under_review",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("accepted_risk", "Accepted Risk"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_regulatory_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_artefacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="regulatory_requirements",
                        to="compliance.governanceartefact",
                    ),
                ),
                (
                    "linked_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="regulatory_requirements",
                        to="catalogs.control",
                    ),
                ),
                (
                    "linked_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="regulatory_requirements",
                        to="core.document",
                    ),
                ),
                (
                    "linked_frameworks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="regulatory_requirements",
                        to="catalogs.framework",
                    ),
                ),
                (
                    "linked_risks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="regulatory_requirements",
                        to="risk.risk",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_regulatory_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "title"],
            },
        ),
        migrations.CreateModel(
            name="NonConformity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonconformity_id", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("critical", "Critical"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("root_cause_review", "Root Cause Review"),
                            ("corrective_action", "Corrective Action"),
                            ("verification", "Verification"),
                            ("closed", "Closed"),
                            ("accepted", "Accepted"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("internal_audit", "Internal Audit"),
                            ("external_audit", "External Audit"),
                            ("assessment", "Assessment"),
                            ("incident", "Incident"),
                            ("management_review", "Management Review"),
                            ("vendor_review", "Vendor Review"),
                            ("other", "Other"),
                        ],
                        default="assessment",
                        max_length=30,
                    ),
                ),
                ("detected_on", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("closed_on", models.DateField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nonconformities",
                        to="catalogs.control",
                    ),
                ),
                (
                    "linked_documents",
                    models.ManyToManyField(
                        blank=True, related_name="nonconformities", to="core.document"
                    ),
                ),
                (
                    "linked_risks",
                    models.ManyToManyField(
                        blank=True, related_name="nonconformities", to="risk.risk"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_nonconformities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raised_nonconformities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regulatory_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nonconformities",
                        to="compliance.regulatoryrequirement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Non-conformities",
                "ordering": ["-detected_on", "severity", "title"],
            },
        ),
        migrations.CreateModel(
            name="ManagementReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("held", "Held"),
                            ("actions_open", "Actions Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("meeting_date", models.DateField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True)),
                ("minutes", models.TextField(blank=True)),
                ("decisions", models.TextField(blank=True)),
                ("actions_summary", models.TextField(blank=True)),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("outputs", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="management_review_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chaired_management_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_management_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_artefacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="management_reviews",
                        to="compliance.governanceartefact",
                    ),
                ),
                (
                    "linked_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="management_reviews",
                        to="catalogs.control",
                    ),
                ),
                (
                    "linked_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="management_reviews",
                        to="core.document",
                    ),
                ),
                (
                    "linked_nonconformities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="management_reviews",
                        to="compliance.nonconformity",
                    ),
                ),
                (
                    "linked_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="management_reviews",
                        to="compliance.regulatoryrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-meeting_date", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="governanceartefact",
            index=models.Index(
                fields=["artefact_type", "status"],
                name="compliance__artefac_19326c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governanceartefact",
            index=models.Index(
                fields=["owner", "status"], name="compliance__owner_i_7f5399_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="governanceartefact",
            index=models.Index(
                fields=["review_due_date"], name="compliance__review__792545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoryrequirement",
            index=models.Index(
                fields=["source_type", "applicability_status"],
                name="compliance__source__666a07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoryrequirement",
            index=models.Index(
                fields=["compliance_status", "priority"],
                name="compliance__complia_b878dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoryrequirement",
            index=models.Index(
                fields=["owner", "compliance_status"],
                name="compliance__owner_i_3c7208_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoryrequirement",
            index=models.Index(
                fields=["next_review_date"], name="compliance__next_re_b9bbbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["status", "severity"], name="compliance__status_107e0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["owner", "status"], name="compliance__owner_i_74aec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["due_date"], name="compliance__due_dat_c09a57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["source_type"], name="compliance__source__6fcd4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="managementreview",
            index=models.Index(
                fields=["status", "meeting_date"], name="compliance__status_85e6af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="managementreview",
            index=models.Index(
                fields=["chair", "status"], name="compliance__chair_i_8ff936_idx"
            ),
        ),
    ]
