# Generated by Django 5.0.6 on 2025-08-25 15:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_purpose', models.CharField(blank=True, help_text='Purpose of this evidence for the assessment', max_length=100)),
                ('is_primary_evidence', models.BooleanField(default=False, help_text='Whether this is primary evidence for the assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reminders', models.BooleanField(default=True, help_text='Whether to send automated reminders to this user')),
                ('advance_warning_days', models.PositiveIntegerField(default=7, help_text='Days before due date to send first reminder')),
                ('overdue_reminders', models.BooleanField(default=True, help_text='Whether to send reminders for overdue assessments')),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='daily', help_text='How frequently to send overdue reminders', max_length=10)),
                ('custom_reminder_days', models.JSONField(blank=True, default=list, help_text='Custom days for reminders (e.g., [1, 3, 7] for 1, 3, and 7 days before)')),
                ('email_notifications', models.BooleanField(default=True, help_text='Whether to send email notifications')),
                ('include_assessment_details', models.BooleanField(default=True, help_text='Whether to include detailed assessment information in emails')),
                ('include_remediation_items', models.BooleanField(default=True, help_text='Whether to include remediation due dates in reminders')),
                ('daily_digest_enabled', models.BooleanField(default=False, help_text='Whether to send daily digest of all upcoming/overdue items')),
                ('weekly_digest_enabled', models.BooleanField(default=True, help_text='Whether to send weekly digest of upcoming assessments')),
                ('digest_day_of_week', models.PositiveIntegerField(default=1, help_text='Day of week for weekly digest (0=Sunday, 1=Monday, etc.)')),
                ('silence_completed_assessments', models.BooleanField(default=True, help_text='Stop sending reminders for completed assessments')),
                ('silence_not_applicable', models.BooleanField(default=True, help_text="Don't send reminders for assessments marked as not applicable")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Reminder Configuration',
                'verbose_name_plural': 'Assessment Reminder Configurations',
            },
        ),
        migrations.CreateModel(
            name='AssessmentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('advance_warning', 'Advance Warning'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('weekly_digest', 'Weekly Digest'), ('daily_digest', 'Daily Digest')], max_length=20)),
                ('days_before_due', models.IntegerField(blank=True, help_text='Days before due date when reminder was sent (negative for overdue)', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_id', models.CharField(help_text='Framework-specific clause identifier (e.g., CC6.1, A.8.2.1)', max_length=50)),
                ('title', models.CharField(help_text='Clause title or heading', max_length=300)),
                ('description', models.TextField(help_text='Full clause text and requirements')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within framework')),
                ('clause_type', models.CharField(choices=[('control', 'Control Requirement'), ('policy', 'Policy Requirement'), ('procedure', 'Procedure Requirement'), ('documentation', 'Documentation Requirement'), ('assessment', 'Assessment Requirement'), ('monitoring', 'Monitoring Requirement'), ('reporting', 'Reporting Requirement')], default='control', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_testable', models.BooleanField(default=True, help_text='Whether this clause can be tested/audited')),
                ('implementation_guidance', models.TextField(blank=True, help_text='Guidance on how to implement this clause')),
                ('testing_procedures', models.TextField(blank=True, help_text='Procedures for testing compliance with this clause')),
                ('external_references', models.JSONField(blank=True, default=dict, help_text='References to other standards, regulations, or frameworks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['framework', 'sort_order', 'clause_id'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Control name or title', max_length=200)),
                ('description', models.TextField(help_text='Detailed control description')),
                ('control_id', models.CharField(help_text='Unique control identifier', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Control ID must start with alphanumeric and contain only uppercase letters, numbers, hyphens, and dots', regex='^[A-Z0-9][A-Z0-9\\-\\.]*$')])),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive Control'), ('detective', 'Detective Control'), ('corrective', 'Corrective Control'), ('compensating', 'Compensating Control'), ('administrative', 'Administrative Control'), ('technical', 'Technical Control'), ('physical', 'Physical Control')], max_length=20)),
                ('automation_level', models.CharField(choices=[('manual', 'Manual Control'), ('semi_automated', 'Semi-Automated Control'), ('automated', 'Automated Control'), ('continuous', 'Continuous Monitoring')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('testing', 'Under Testing'), ('active', 'Active'), ('remediation', 'Needs Remediation'), ('disabled', 'Disabled'), ('retired', 'Retired')], default='planned', max_length=20)),
                ('business_owner', models.CharField(blank=True, help_text='Business unit or department responsible', max_length=200)),
                ('implementation_details', models.TextField(blank=True, help_text='Specific implementation steps and procedures')),
                ('frequency', models.CharField(blank=True, help_text='How often this control is performed (e.g., daily, monthly, annually)', max_length=100)),
                ('last_tested_date', models.DateField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, choices=[('not_effective', 'Not Effective'), ('partially_effective', 'Partially Effective'), ('largely_effective', 'Largely Effective'), ('fully_effective', 'Fully Effective')], max_length=20)),
                ('effectiveness_rating', models.CharField(blank=True, choices=[('not_effective', 'Not Effective'), ('partially_effective', 'Partially Effective'), ('largely_effective', 'Largely Effective'), ('fully_effective', 'Fully Effective')], help_text='Current effectiveness assessment', max_length=20)),
                ('evidence_requirements', models.TextField(blank=True, help_text="What evidence is needed to demonstrate this control's effectiveness")),
                ('documentation_links', models.JSONField(blank=True, default=list, help_text='Links to related policies, procedures, and documentation')),
                ('risk_rating', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Risk level if this control fails', max_length=10)),
                ('remediation_plan', models.TextField(blank=True, help_text='Plan for addressing control deficiencies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('change_log', models.JSONField(blank=True, default=list, help_text='History of changes to this control')),
            ],
            options={
                'ordering': ['control_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(help_text='Unique assessment identifier', max_length=100, unique=True)),
                ('applicability', models.CharField(choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable'), ('to_be_determined', 'To Be Determined')], default='to_be_determined', help_text='Whether this control applies to the organization', max_length=20)),
                ('applicability_rationale', models.TextField(blank=True, help_text="Explanation of why the control is/isn't applicable")),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('complete', 'Complete'), ('not_applicable', 'Not Applicable'), ('deferred', 'Deferred')], default='not_started', help_text='Current assessment status', max_length=20)),
                ('implementation_status', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('partially_implemented', 'Partially Implemented'), ('implemented', 'Implemented'), ('not_applicable', 'Not Applicable')], default='not_implemented', help_text='Current implementation status of the control', max_length=25)),
                ('due_date', models.DateField(blank=True, help_text='Target completion date for this assessment', null=True)),
                ('started_date', models.DateField(blank=True, help_text='Date when assessment work began', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='Date when assessment was completed', null=True)),
                ('current_state_description', models.TextField(blank=True, help_text='Description of the current state of control implementation')),
                ('target_state_description', models.TextField(blank=True, help_text='Description of the desired future state')),
                ('gap_analysis', models.TextField(blank=True, help_text='Analysis of gaps between current and target state')),
                ('implementation_approach', models.TextField(blank=True, help_text='Planned or implemented approach for addressing this control')),
                ('maturity_level', models.CharField(blank=True, choices=[('ad_hoc', 'Ad Hoc'), ('repeatable', 'Repeatable'), ('defined', 'Defined'), ('managed', 'Managed'), ('optimized', 'Optimized')], help_text='Current maturity level of control implementation', max_length=20)),
                ('risk_rating', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Risk level if this control is not properly implemented', max_length=10)),
                ('compliance_score', models.PositiveIntegerField(blank=True, help_text='Compliance score (0-100) for this control', null=True)),
                ('assessment_notes', models.TextField(blank=True, help_text='General notes and observations about this assessment')),
                ('reviewer_comments', models.TextField(blank=True, help_text='Comments from the reviewer')),
                ('remediation_plan', models.TextField(blank=True, help_text='Plan for addressing gaps and improving control implementation')),
                ('remediation_due_date', models.DateField(blank=True, help_text='Target date for completing remediation activities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Assessment version number')),
                ('change_log', models.JSONField(blank=True, default=list, help_text='History of changes to this assessment')),
            ],
            options={
                'ordering': ['control__control_id', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ControlEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Evidence title or description', max_length=200)),
                ('evidence_type', models.CharField(choices=[('document', 'Document/Policy'), ('screenshot', 'Screenshot'), ('log_file', 'Log File'), ('report', 'Report'), ('certificate', 'Certificate'), ('approval', 'Approval/Sign-off'), ('test_result', 'Test Result'), ('meeting_notes', 'Meeting Notes'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional evidence description')),
                ('external_url', models.URLField(blank=True, help_text='External URL for evidence (e.g., system screenshot)', null=True)),
                ('evidence_date', models.DateField(default=django.utils.timezone.now, help_text='Date when evidence was created or collected')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether evidence has been validated')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-evidence_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Framework name (e.g., SOC 2 Type II)', max_length=200)),
                ('short_name', models.CharField(help_text='Short identifier (e.g., SOC2)', max_length=50)),
                ('description', models.TextField(help_text='Framework description and purpose')),
                ('framework_type', models.CharField(choices=[('security', 'Security Framework'), ('privacy', 'Privacy Framework'), ('financial', 'Financial Framework'), ('operational', 'Operational Framework'), ('industry', 'Industry-Specific Framework'), ('custom', 'Custom Framework')], default='security', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External framework identifier or reference code', max_length=100, null=True)),
                ('issuing_organization', models.CharField(help_text='Organization that issued/maintains this framework', max_length=200)),
                ('official_url', models.URLField(blank=True, help_text='Official framework documentation URL', null=True)),
                ('version', models.CharField(default='1.0', help_text='Framework version', max_length=50)),
                ('effective_date', models.DateField(help_text='Date when this version became effective')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when this version expires', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether compliance with this framework is mandatory for the organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_from', models.CharField(blank=True, help_text='Source of framework import (file, API, manual entry)', max_length=200)),
                ('import_checksum', models.CharField(blank=True, help_text='Checksum for tracking changes in imported frameworks', max_length=64)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('equivalent', 'Equivalent Requirements'), ('partial', 'Partially Overlapping'), ('supports', 'Supporting Requirement'), ('related', 'Related Requirement')], max_length=20)),
                ('mapping_rationale', models.TextField(blank=True, help_text='Explanation of why these clauses are mapped together')),
                ('confidence_level', models.IntegerField(default=75, help_text='Confidence percentage (0-100) in this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
