# Generated by Django 5.0.6 on 2025-08-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentevidence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentreminderconfiguration',
            name='user',
            field=models.OneToOneField(help_text='User for whom reminders are configured', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentreminderlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_reminder_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clause',
            name='parent_clause',
            field=models.ForeignKey(blank=True, help_text='Parent clause for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclauses', to='catalogs.clause'),
        ),
        migrations.AddField(
            model_name='control',
            name='clauses',
            field=models.ManyToManyField(help_text='Framework clauses this control addresses', related_name='controls', to='catalogs.clause'),
        ),
        migrations.AddField(
            model_name='control',
            name='control_owner',
            field=models.ForeignKey(help_text='Person responsible for this control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Person responsible for completing this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='control',
            field=models.ForeignKey(help_text='The control being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='catalogs.control'),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='created_by',
            field=models.ForeignKey(help_text='Person who created this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='remediation_owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for remediation activities', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Person responsible for reviewing this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentreminderlog',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='catalogs.controlassessment'),
        ),
        migrations.AddField(
            model_name='assessmentevidence',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='catalogs.controlassessment'),
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='collected_by',
            field=models.ForeignKey(help_text='Person who collected this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='catalogs.control'),
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Associated document file', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Person who validated this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentevidence',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='catalogs.controlevidence'),
        ),
        migrations.AddField(
            model_name='framework',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_frameworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clause',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='catalogs.framework'),
        ),
        migrations.AddField(
            model_name='frameworkmapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frameworkmapping',
            name='source_clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='catalogs.clause'),
        ),
        migrations.AddField(
            model_name='frameworkmapping',
            name='target_clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='catalogs.clause'),
        ),
        migrations.AddField(
            model_name='frameworkmapping',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['status', 'control_type'], name='catalogs_co_status_47e287_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['control_owner'], name='catalogs_co_control_bc17b4_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['automation_level'], name='catalogs_co_automat_e865af_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['last_tested_date'], name='catalogs_co_last_te_872093_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['effectiveness_rating'], name='catalogs_co_effecti_424844_idx'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['status', 'due_date'], name='catalogs_co_status_acf9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['applicability', 'implementation_status'], name='catalogs_co_applica_69dc37_idx'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['assigned_to', 'status'], name='catalogs_co_assigne_035fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['control', 'status'], name='catalogs_co_control_bfb644_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlassessment',
            unique_together={('control', 'assessment_id')},
        ),
        migrations.AddIndex(
            model_name='assessmentreminderlog',
            index=models.Index(fields=['assessment', 'user'], name='catalogs_as_assessm_dc97bf_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentreminderlog',
            index=models.Index(fields=['sent_at'], name='catalogs_as_sent_at_8cc127_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentreminderlog',
            index=models.Index(fields=['reminder_type'], name='catalogs_as_reminde_f93f75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentreminderlog',
            unique_together={('assessment', 'user', 'reminder_type', 'days_before_due')},
        ),
        migrations.AddIndex(
            model_name='controlevidence',
            index=models.Index(fields=['control', '-evidence_date'], name='catalogs_co_control_bfd92b_idx'),
        ),
        migrations.AddIndex(
            model_name='controlevidence',
            index=models.Index(fields=['evidence_type'], name='catalogs_co_evidenc_feb157_idx'),
        ),
        migrations.AddIndex(
            model_name='controlevidence',
            index=models.Index(fields=['is_validated'], name='catalogs_co_is_vali_3c79b4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentevidence',
            index=models.Index(fields=['assessment', 'is_primary_evidence'], name='catalogs_as_assessm_34a71d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentevidence',
            unique_together={('assessment', 'evidence')},
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['status', 'framework_type'], name='catalogs_fr_status_7eb9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['short_name'], name='catalogs_fr_short_n_25576f_idx'),
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['is_mandatory', 'status'], name='catalogs_fr_is_mand_2c95eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='framework',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['framework', 'sort_order'], name='catalogs_cl_framewo_f3920d_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['clause_type', 'criticality'], name='catalogs_cl_clause__86cff2_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['is_testable'], name='catalogs_cl_is_test_da8c48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together={('framework', 'clause_id')},
        ),
        migrations.AddIndex(
            model_name='frameworkmapping',
            index=models.Index(fields=['mapping_type'], name='catalogs_fr_mapping_47dd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkmapping',
            index=models.Index(fields=['confidence_level'], name='catalogs_fr_confide_0644ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frameworkmapping',
            unique_together={('source_clause', 'target_clause')},
        ),
    ]
