# Generated by Django 5.2.15 on 2026-07-15 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("standard", "Standard"),
                            ("procedure", "Procedure"),
                            ("iso_mandatory", "ISO Mandatory Document"),
                            ("pci", "PCI"),
                            ("risk", "Risk"),
                            ("asset", "Asset"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("standard", "Standard"),
                            ("procedure", "Procedure"),
                            ("mandatory_document", "Mandatory Document"),
                            ("risk_register", "Risk Register"),
                            ("asset_register", "Asset Register"),
                            ("framework_spreadsheet", "Framework Spreadsheet"),
                            ("template", "Template"),
                            ("sample", "Sample"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_code", models.CharField(blank=True, max_length=80)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("source_filename", models.CharField(max_length=255)),
                ("source_checksum", models.CharField(max_length=64)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_documents",
                        to="catalogs.clause",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_documents",
                        to="catalogs.control",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_records",
                        to="core.document",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_documents",
                        to="catalogs.framework",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_template_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["module", "document_type", "title"],
                "indexes": [
                    models.Index(
                        fields=["module", "document_type"],
                        name="catalogs_te_module_d19f9e_idx",
                    ),
                    models.Index(
                        fields=["framework"], name="catalogs_te_framewo_c0b0e5_idx"
                    ),
                    models.Index(
                        fields=["clause"], name="catalogs_te_clause__62d335_idx"
                    ),
                    models.Index(
                        fields=["control"], name="catalogs_te_control_526d6f_idx"
                    ),
                    models.Index(
                        fields=["source_checksum"],
                        name="catalogs_te_source__499a7d_idx",
                    ),
                ],
            },
        ),
    ]
