# Generated by Django 5.2.15 on 2026-07-16 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_templatedocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="controlassessment",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                help_text="Framework version this assessment was created against",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_assessments",
                to="catalogs.framework",
            ),
        ),
        migrations.AddIndex(
            model_name="controlassessment",
            index=models.Index(
                fields=["framework", "status"], name="catalogs_co_framewo_952a7c_idx"
            ),
        ),
    ]
