# Generated by Django 5.0.6 on 2025-08-22 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('device_token', models.TextField(help_text='Push notification device token')),
                ('device_name', models.CharField(help_text='User-friendly device name', max_length=100)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Browser')], max_length=20)),
                ('push_service', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification Service'), ('web_push', 'Web Push')], max_length=20)),
                ('pending_challenge', models.TextField(blank=True, help_text='JSON data for pending auth challenge')),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Device',
            },
        ),
        migrations.CreateModel(
            name='UserDevicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_method', models.CharField(choices=[('email', 'Email OTP'), ('totp', 'Authenticator App'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('fallback_methods', models.JSONField(default=list, help_text='Ordered list of fallback methods')),
                ('require_2fa_for_sensitive_actions', models.BooleanField(default=True)),
                ('remember_device_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
