# Generated by Django 5.2.15 on 2026-07-15 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0003_templatedocument"),
        ("core", "0001_initial"),
        ("risk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("workstation", "Workstation"),
                            ("monitor", "Monitor"),
                            ("mobile_device", "Mobile Device"),
                            ("printer", "Printer"),
                            ("infrastructure", "Infrastructure"),
                            ("application", "Application"),
                            ("database", "Database"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=30,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                            ("disposed", "Disposed"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=255)),
                ("custodian", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=64)),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("operating_system", models.CharField(blank=True, max_length=255)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("disposal_date", models.DateField(blank=True, null=True)),
                ("source_path", models.CharField(blank=True, max_length=500)),
                ("source_sheet", models.CharField(blank=True, max_length=120)),
                ("source_row", models.PositiveIntegerField(blank=True, null=True)),
                ("source_checksum", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_controls",
                    models.ManyToManyField(
                        blank=True, related_name="linked_assets", to="catalogs.control"
                    ),
                ),
                (
                    "linked_documents",
                    models.ManyToManyField(
                        blank=True, related_name="linked_assets", to="core.document"
                    ),
                ),
                (
                    "linked_risks",
                    models.ManyToManyField(
                        blank=True, related_name="linked_assets", to="risk.risk"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["asset_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssetReviewReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("advance_warning", "Advance Warning"),
                            ("due_today", "Due Today"),
                            ("overdue", "Overdue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("review_date", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reminder_logs",
                        to="assets.asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_review_reminder_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["asset_type", "lifecycle_status"],
                name="assets_asse_asset_t_a2563e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["criticality"], name="assets_asse_critica_a56ae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["classification"], name="assets_asse_classif_5c1677_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["owner"], name="assets_asse_owner_i_bd5223_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["next_review_date"], name="assets_asse_next_re_012d34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["source_checksum"], name="assets_asse_source__3dd042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetreviewreminderlog",
            index=models.Index(
                fields=["asset", "owner"], name="assets_asse_asset_i_797df1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetreviewreminderlog",
            index=models.Index(
                fields=["review_date", "reminder_type"],
                name="assets_asse_review__0017dc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetreviewreminderlog",
            unique_together={("asset", "owner", "reminder_type", "review_date")},
        ),
    ]
