# Generated by Django 5.0.6 on 2025-08-25 15:58

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_documents', models.PositiveIntegerField(default=100)),
                ('max_frameworks', models.PositiveIntegerField(default=1)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_advanced_reporting', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload documents (PDF, DOC, XLS, etc.)', upload_to=core.models.tenant_file_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=False, help_text='Whether file can be accessed without authentication')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.document')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_grandfathered', models.BooleanField(default=False)),
                ('seats_included', models.PositiveIntegerField(default=5)),
                ('custom_max_users', models.PositiveIntegerField(blank=True, help_text="Override plan's max users limit", null=True)),
                ('custom_max_documents', models.PositiveIntegerField(blank=True, help_text="Override plan's max documents limit", null=True)),
                ('custom_max_frameworks', models.PositiveIntegerField(blank=True, help_text="Override plan's max frameworks limit", null=True)),
                ('custom_max_storage_gb', models.PositiveIntegerField(blank=True, help_text="Override plan's max storage limit", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LimitOverrideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('max_users', 'Maximum Users'), ('max_documents', 'Maximum Documents'), ('max_frameworks', 'Maximum Frameworks'), ('max_storage_gb', 'Maximum Storage (GB)')], max_length=20)),
                ('current_limit', models.PositiveIntegerField()),
                ('requested_limit', models.PositiveIntegerField()),
                ('business_justification', models.TextField(help_text='Explain why this limit increase is needed')),
                ('urgency', models.CharField(choices=[('low', 'Low - Standard Review'), ('medium', 'Medium - 24 Hour Review'), ('high', 'High - Same Day Review'), ('critical', 'Critical - Immediate Review')], default='low', max_length=10)),
                ('temporary', models.BooleanField(default=False, help_text='Is this a temporary increase?')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When should temporary limits expire?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('requested_by', models.CharField(help_text='User who requested the override', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('first_approver', models.CharField(blank=True, max_length=255, null=True)),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('first_approval_notes', models.TextField(blank=True)),
                ('second_approver', models.CharField(blank=True, max_length=255, null=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approval_notes', models.TextField(blank=True)),
                ('final_decision_by', models.CharField(blank=True, max_length=255, null=True)),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_override_requests', to='core.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('invoice.payment_succeeded', 'Invoice Payment Succeeded'), ('invoice.payment_failed', 'Invoice Payment Failed'), ('customer.subscription.created', 'Subscription Created'), ('customer.subscription.updated', 'Subscription Updated'), ('customer.subscription.deleted', 'Subscription Deleted'), ('checkout.session.completed', 'Checkout Completed')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='core_docume_uploade_9a4f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_public'], name='core_docume_is_publ_23d639_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['document', '-accessed_at'], name='core_docume_documen_c93c84_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['accessed_by', '-accessed_at'], name='core_docume_accesse_899684_idx'),
        ),
        migrations.AddIndex(
            model_name='limitoverriderequest',
            index=models.Index(fields=['subscription', 'status'], name='core_limito_subscri_64835a_idx'),
        ),
        migrations.AddIndex(
            model_name='limitoverriderequest',
            index=models.Index(fields=['status', '-created_at'], name='core_limito_status_ff56f8_idx'),
        ),
        migrations.AddIndex(
            model_name='limitoverriderequest',
            index=models.Index(fields=['urgency', '-created_at'], name='core_limito_urgency_cba02d_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['stripe_event_id'], name='core_billin_stripe__1f53d1_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['event_type', '-created_at'], name='core_billin_event_t_a7e6af_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['processed'], name='core_billin_process_7c46fb_idx'),
        ),
    ]
