# Generated by Django 5.2.15 on 2026-07-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="included_modules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="subscription",
            name="enabled_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Explicit module grants for this subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_module",
            field=models.CharField(
                blank=True,
                help_text="Single module selected for a trial subscription",
                max_length=40,
            ),
        ),
    ]
