# Generated by Django 5.2.15 on 2026-07-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_plan_included_modules_subscription_enabled_modules_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"ordering": ["-at"]},
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event", "-at"], name="core_audite_event_b0b952_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["user", "-at"], name="core_audite_user_id_3d7c61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["at"], name="core_audite_at_aa875b_idx"),
        ),
    ]
