# Generated by Django 5.2.16 on 2026-08-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tenant_tax_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("invoice.payment_succeeded", "Invoice Payment Succeeded"),
                    ("invoice.payment_failed", "Invoice Payment Failed"),
                    ("invoice.finalized", "Invoice Finalized"),
                    ("invoice.updated", "Invoice Updated"),
                    ("invoice.voided", "Invoice Voided"),
                    ("customer.subscription.created", "Subscription Created"),
                    ("customer.subscription.updated", "Subscription Updated"),
                    ("customer.subscription.deleted", "Subscription Deleted"),
                    ("checkout.session.completed", "Checkout Completed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=255, unique=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("invoice_number", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("uncollectible", "Uncollectible"),
                            ("void", "Void"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("subtotal", models.BigIntegerField(default=0)),
                ("tax_amount", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField(default=0)),
                ("amount_due", models.BigIntegerField(default=0)),
                ("amount_paid", models.BigIntegerField(default=0)),
                ("hosted_invoice_url", models.URLField(blank=True)),
                ("invoice_pdf", models.URLField(blank=True)),
                ("tax_status", models.CharField(blank=True, max_length=30)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("source_event_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_evidence",
                        to="core.subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_evidence",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
