# Generated by Django 4.2.23 on 2026-07-12 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(
                        help_text="Unique vendor identifier (auto-generated: VEN-YYYY-NNNN)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Official legal business name if different from common name",
                        max_length=200,
                    ),
                ),
                (
                    "business_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of vendor's business and services provided",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax ID, EIN, or equivalent business identifier",
                        max_length=50,
                    ),
                ),
                (
                    "duns_number",
                    models.CharField(
                        blank=True,
                        help_text="D-U-N-S Number for business identification",
                        max_length=20,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="under_review",
                        max_length=20,
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("service_provider", "Service Provider"),
                            ("consultant", "Consultant"),
                            ("contractor", "Contractor"),
                            ("partner", "Strategic Partner"),
                            ("subcontractor", "Subcontractor"),
                        ],
                        default="supplier",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated risk score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "annual_spend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual spend with this vendor",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("credit_rating", models.CharField(blank=True, max_length=10)),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Standard payment terms (e.g., Net 30, Net 60)",
                        max_length=50,
                    ),
                ),
                (
                    "operating_regions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of regions where this vendor operates (e.g., ['US', 'EU', 'APAC'])",
                    ),
                ),
                (
                    "primary_region",
                    models.CharField(
                        blank=True,
                        help_text="Primary operating region code for due diligence requirements",
                        max_length=10,
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Region-specific custom fields and their values",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of relevant certifications (ISO, SOC, etc.)",
                    ),
                ),
                (
                    "compliance_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Compliance status for various requirements",
                    ),
                ),
                (
                    "data_processing_agreement",
                    models.BooleanField(
                        default=False, help_text="Data Processing Agreement in place"
                    ),
                ),
                (
                    "security_assessment_completed",
                    models.BooleanField(
                        default=False, help_text="Security assessment completed"
                    ),
                ),
                ("security_assessment_date", models.DateField(blank=True, null=True)),
                (
                    "relationship_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date relationship with vendor began",
                        null=True,
                    ),
                ),
                (
                    "primary_contract_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "auto_renewal",
                    models.BooleanField(
                        default=False, help_text="Contract has automatic renewal clause"
                    ),
                ),
                (
                    "renewal_notice_days",
                    models.IntegerField(
                        default=90,
                        help_text="Days notice required for contract renewal/termination",
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall performance score (0-100)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("last_performance_review", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes and comments about the vendor",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and filtering",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary relationship manager for this vendor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="Internal service code or SKU",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("it_services", "IT Services"),
                            ("cloud_hosting", "Cloud Hosting"),
                            ("software_licensing", "Software Licensing"),
                            ("consulting", "Consulting"),
                            ("support_maintenance", "Support & Maintenance"),
                            ("professional_services", "Professional Services"),
                            ("managed_services", "Managed Services"),
                            ("security_services", "Security Services"),
                            ("data_processing", "Data Processing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        help_text="Highest classification of data processed by this service",
                        max_length=20,
                    ),
                ),
                (
                    "risk_assessment_required",
                    models.BooleanField(
                        default=True,
                        help_text="Service requires formal risk assessment",
                    ),
                ),
                ("risk_assessment_completed", models.BooleanField(default=False)),
                ("risk_assessment_date", models.DateField(blank=True, null=True)),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor", "name"],
            },
        ),
        migrations.CreateModel(
            name="VendorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("meeting", "Meeting Notes"),
                            ("issue", "Issue/Problem"),
                            ("performance", "Performance Review"),
                            ("contract", "Contract Discussion"),
                            ("security", "Security Assessment"),
                            ("compliance", "Compliance Review"),
                            ("renewal", "Renewal Discussion"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Internal note not visible to vendor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_notes",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Contact"),
                            ("billing", "Billing Contact"),
                            ("technical", "Technical Contact"),
                            ("legal", "Legal Contact"),
                            ("security", "Security Contact"),
                            ("account_manager", "Account Manager"),
                            ("executive", "Executive Contact"),
                            ("emergency", "Emergency Contact"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary contact for this vendor"
                    ),
                ),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("mobile", "Mobile"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this contact"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "contact_type", "first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="VendorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color_code",
                    models.CharField(
                        default="#6c757d",
                        help_text="Hex color code for visual identification (e.g., #0066cc)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "risk_weight",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="medium",
                        help_text="Default risk level for vendors in this category",
                        max_length=10,
                    ),
                ),
                (
                    "compliance_requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Category-specific compliance requirements and standards",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Vendor Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="vendors_ven_name_4cddbc_idx"),
                    models.Index(
                        fields=["risk_weight"], name="vendors_ven_risk_we_7e9afb_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary vendor category for classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendors.vendorcategory",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_vendors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RegionalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        help_text="Region code (e.g., US, EU, APAC, CA, UK)",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid region code (e.g., US, EU, APAC)",
                                regex="^[A-Z]{2,10}$",
                            )
                        ],
                    ),
                ),
                ("region_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "required_fields",
                    models.JSONField(
                        default=dict,
                        help_text="JSON configuration defining which standard fields are required in this region",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        default=list,
                        help_text="JSON array defining additional custom fields required for this region",
                    ),
                ),
                (
                    "compliance_standards",
                    models.JSONField(
                        default=list,
                        help_text="List of compliance standards applicable to this region",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        default=dict,
                        help_text="Custom validation rules for fields in this region",
                    ),
                ),
                (
                    "data_processing_requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Specific data processing and privacy requirements",
                    ),
                ),
                (
                    "contract_requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Region-specific contract terms and requirements",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Regional Configuration",
                "verbose_name_plural": "Regional Configurations",
                "ordering": ["region_code"],
                "indexes": [
                    models.Index(
                        fields=["region_code"], name="vendors_reg_region__d36293_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="vendors_reg_is_acti_7e717e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="Unique task identifier (auto-generated: TSK-YYYY-NNNN)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("contract_renewal", "Contract Renewal"),
                            ("contract_renegotiation", "Contract Renegotiation"),
                            ("security_review", "Security Assessment/Review"),
                            ("compliance_assessment", "Compliance Assessment"),
                            ("performance_review", "Performance Review"),
                            ("risk_assessment", "Risk Assessment"),
                            ("audit", "Vendor Audit"),
                            ("certification_renewal", "Certification Renewal"),
                            ("policy_review", "Policy Review"),
                            ("onboarding", "Vendor Onboarding"),
                            ("offboarding", "Vendor Offboarding"),
                            (
                                "data_processing_agreement",
                                "Data Processing Agreement Review",
                            ),
                            ("insurance_verification", "Insurance Verification"),
                            ("financial_review", "Financial Review"),
                            ("custom", "Custom Task"),
                        ],
                        help_text="Type of vendor-related task",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title for the task", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the task requirements",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Date when the task is due for completion"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional start date for the task",
                        null=True,
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, help_text="Actual completion timestamp", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "reminder_days",
                    models.JSONField(
                        default=vendors.models.default_reminder_days,
                        help_text="Days before due date to send reminders (e.g., [30, 14, 7, 1])",
                    ),
                ),
                (
                    "last_reminder_sent",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last reminder sent",
                        null=True,
                    ),
                ),
                (
                    "reminder_recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional email addresses for reminders",
                    ),
                ),
                (
                    "related_contract_number",
                    models.CharField(
                        blank=True,
                        help_text="Related contract number if applicable",
                        max_length=100,
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about task completion, results, or outcomes",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="References to attached documents or evidence",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this task repeats on a schedule",
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for recurring tasks (frequency, interval, etc.)",
                    ),
                ),
                (
                    "auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this task was automatically generated from contract dates",
                    ),
                ),
                (
                    "generation_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of automatic generation (e.g., 'contract_expiry', 'security_review')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for completing this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vendor_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendor_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent task if this is a recurring instance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_instances",
                        to="vendors.vendortask",
                    ),
                ),
                (
                    "service_reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related vendor service if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendors.vendorservice",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Associated vendor for this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Task",
                "verbose_name_plural": "Vendor Tasks",
                "ordering": ["due_date", "priority"],
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="vendors_ven_task_id_acd0b6_idx"
                    ),
                    models.Index(
                        fields=["vendor", "due_date"],
                        name="vendors_ven_vendor__df7fc9_idx",
                    ),
                    models.Index(
                        fields=["due_date", "status"],
                        name="vendors_ven_due_dat_e780f2_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="vendors_ven_assigne_b206e3_idx",
                    ),
                    models.Index(
                        fields=["task_type"], name="vendors_ven_task_ty_0ae5cd_idx"
                    ),
                    models.Index(
                        fields=["priority", "due_date"],
                        name="vendors_ven_priorit_beb11a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="vendors_ven_status_b9eefd_idx"
                    ),
                    models.Index(
                        fields=["auto_generated"], name="vendors_ven_auto_ge_1d9747_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="vendors_ven_created_e783b9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vendorservice",
            index=models.Index(
                fields=["vendor", "category"], name="vendors_ven_vendor__2dcc61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorservice",
            index=models.Index(
                fields=["data_classification"], name="vendors_ven_data_cl_10b782_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorservice",
            index=models.Index(
                fields=["risk_assessment_required"],
                name="vendors_ven_risk_as_3e8988_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorservice",
            index=models.Index(
                fields=["is_active"], name="vendors_ven_is_acti_67f64a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorservice",
            unique_together={("vendor", "name")},
        ),
        migrations.AddIndex(
            model_name="vendornote",
            index=models.Index(
                fields=["vendor", "-created_at"], name="vendors_ven_vendor__0f5c34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornote",
            index=models.Index(
                fields=["note_type"], name="vendors_ven_note_ty_87b8a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendornote",
            index=models.Index(
                fields=["created_by"], name="vendors_ven_created_24cfed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcontact",
            index=models.Index(
                fields=["vendor", "contact_type"], name="vendors_ven_vendor__235728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcontact",
            index=models.Index(fields=["email"], name="vendors_ven_email_d539c5_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorcontact",
            index=models.Index(
                fields=["is_primary"], name="vendors_ven_is_prim_d9365d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorcontact",
            unique_together={("vendor", "email")},
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["vendor_id"], name="vendors_ven_vendor__62f878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["name"], name="vendors_ven_name_0d60a8_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["status"], name="vendors_ven_status_2dcb2a_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["risk_level"], name="vendors_ven_risk_le_9584ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["category"], name="vendors_ven_categor_3a7db7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["assigned_to"], name="vendors_ven_assigne_65e780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["contract_end_date"], name="vendors_ven_contrac_88861c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["created_at"], name="vendors_ven_created_c4e3ec_idx"
            ),
        ),
    ]
