# Generated by Django 5.2.15 on 2026-07-15 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "module_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("frameworks", "Frameworks and assessments"),
                            ("risk", "Risk"),
                            ("assets", "Assets"),
                            ("vendors", "Vendors"),
                            ("policies", "Policies"),
                            ("training", "Training"),
                            ("analytics", "Analytics"),
                            ("vulnerability_scanning", "Vulnerability scanning"),
                            ("exports", "Exports"),
                            ("administration", "Administration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowledge_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField()),
                (
                    "module_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("frameworks", "Frameworks and assessments"),
                            ("risk", "Risk"),
                            ("assets", "Assets"),
                            ("vendors", "Vendors"),
                            ("policies", "Policies"),
                            ("training", "Training"),
                            ("analytics", "Analytics"),
                            ("vulnerability_scanning", "Vulnerability scanning"),
                            ("exports", "Exports"),
                            ("administration", "Administration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("workflow_key", models.CharField(blank=True, max_length=80)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "content_scope",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("global", "Axim-managed global"),
                        ],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowledge_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_knowledge_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="knowledge.knowledgecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="knowledge.knowledgearticle",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_article_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "-changed_at"],
                        name="knowledge_k_article_e44f9d_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgecategory",
            index=models.Index(
                fields=["is_active", "module_key"],
                name="knowledge_k_is_acti_99a82e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgecategory",
            index=models.Index(fields=["slug"], name="knowledge_k_slug_17150e_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["status", "module_key"], name="knowledge_k_status_151bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["content_scope", "status"],
                name="knowledge_k_content_d29d4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(fields=["slug"], name="knowledge_k_slug_dae547_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["workflow_key"], name="knowledge_k_workflo_2d4658_idx"
            ),
        ),
    ]
