# Generated by Django 4.2.23 on 2026-07-11 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import policies.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "policy_code",
                    models.CharField(
                        help_text="Unique policy code (e.g., POL-SEC-001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Policy title", max_length=200)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("procedure", "Procedure"),
                            ("policy", "Policy"),
                            ("standard", "Standard"),
                            ("guideline", "Guideline"),
                            ("framework", "Framework"),
                        ],
                        default="policy",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "review_frequency_months",
                    models.PositiveIntegerField(
                        default=12, help_text="How often this policy should be reviewed (in months)"
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="When this policy is due for review", null=True
                    ),
                ),
                (
                    "requires_acknowledgment",
                    models.BooleanField(
                        default=True, help_text="Whether users must acknowledge reading this policy"
                    ),
                ),
                (
                    "acknowledgment_validity_days",
                    models.PositiveIntegerField(
                        default=365, help_text="How long acknowledgments remain valid (days)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this policy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "ordering": ["policy_code", "title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Security, HR, Legal, IT)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this policy category"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for visual identification",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy Category",
                "verbose_name_plural": "Policy Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="Version number (e.g., 1.0, 1.1, 2.0)", max_length=10
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Policy document (PDF, DOCX, or DOC)",
                        upload_to=policies.models.policy_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx", "doc"]
                            )
                        ],
                    ),
                ),
                (
                    "document_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Document size in bytes", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Summary of changes in this version"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Whether this is the current active version"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this version is published and available to users",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When this version becomes effective",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="When this version expires (optional)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_policy_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policy_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Version",
                "verbose_name_plural": "Policy Versions",
                "ordering": ["-version_number"],
                "unique_together": {("policy", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="policies.policycategory",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="owner",
            field=models.ForeignKey(
                help_text="Policy owner/manager responsible for this policy",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PolicyDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("distributed_at", models.DateTimeField(auto_now_add=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distributed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributed_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributed_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="policies.policyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Distribution",
                "verbose_name_plural": "Policy Distributions",
                "ordering": ["-distributed_at"],
                "unique_together": {("policy_version", "distributed_to")},
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address when acknowledgment was made", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Browser user agent string")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this acknowledgment expires", null=True
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="policies.policyversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Acknowledgment",
                "verbose_name_plural": "Policy Acknowledgments",
                "ordering": ["-acknowledged_at"],
                "unique_together": {("user", "policy_version")},
            },
        ),
    ]
