# Generated by Django 5.2.15 on 2026-07-15 20:32

import django.core.validators
import django.db.models.deletion
import policies.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="policyversion",
            name="final_pdf",
            field=models.FileField(
                blank=True,
                help_text="Final PDF generated from the approved editable source",
                null=True,
                upload_to=policies.models.policy_final_pdf_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="final_pdf_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="finalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalized_policy_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("template", "Template"),
                    ("draft", "Draft"),
                    ("client_modified", "Client Modified"),
                    ("approved", "Approved"),
                    ("final", "Final"),
                ],
                default="draft",
                help_text="Document lifecycle state from template through final PDF",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PolicyVersionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("finalized", "Finalized"),
                            ("conversion_failed", "Conversion Failed"),
                            ("downloaded_pdf", "Downloaded PDF"),
                            ("downloaded_source", "Downloaded Source"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_version_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="policies.policyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["policy_version", "-created_at"],
                        name="policies_po_policy__505097_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="policies_po_action_3052b1_idx",
                    ),
                ],
            },
        ),
    ]
