# Generated by Django 5.2.15 on 2026-07-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "policies",
            "0002_policyversion_final_pdf_policyversion_final_pdf_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyversionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("edited", "Edited"),
                    ("published", "Published"),
                    ("activated", "Activated"),
                    ("approved", "Approved"),
                    ("finalized", "Finalized"),
                    ("conversion_failed", "Conversion Failed"),
                    ("distributed", "Distributed"),
                    ("acknowledged", "Acknowledged"),
                    ("downloaded_pdf", "Downloaded PDF"),
                    ("downloaded_source", "Downloaded Source"),
                ],
                max_length=40,
            ),
        ),
    ]
