# Generated by Django 4.2.23 on 2026-07-11 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this SSO provider", max_length=100
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("saml", "SAML 2.0"), ("oauth", "OAuth 2.0 / OpenID Connect")],
                        max_length=10,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        choices=[
                            ("custom", "Custom Configuration"),
                            ("okta", "Okta"),
                            ("azure_ad", "Azure Active Directory"),
                            ("google_workspace", "Google Workspace"),
                            ("microsoft_365", "Microsoft 365"),
                            ("aws_sso", "AWS SSO"),
                            ("onelogin", "OneLogin"),
                            ("auth0", "Auth0"),
                            ("ping_identity", "Ping Identity"),
                        ],
                        default="custom",
                        help_text="Pre-configured provider or custom",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary SSO provider for this tenant"
                    ),
                ),
                (
                    "enforce_sso",
                    models.BooleanField(
                        default=False,
                        help_text="Disable password authentication when SSO is available",
                    ),
                ),
                (
                    "enable_jit_provisioning",
                    models.BooleanField(
                        default=True, help_text="Automatically create user accounts from SSO"
                    ),
                ),
                (
                    "jit_default_role",
                    models.CharField(
                        default="user",
                        help_text="Default role for JIT-provisioned users",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sso_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_providers",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSOSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sso_session_id", models.CharField(blank=True, max_length=255)),
                ("sso_name_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("logged_out", "Logged Out"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "sso_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sso.ssoprovider"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSOAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_attempt", "Login Attempt"),
                            ("login_success", "Login Success"),
                            ("login_failure", "Login Failure"),
                            ("logout", "Logout"),
                            ("jit_provisioning", "JIT User Provisioning"),
                            ("attribute_mapping", "Attribute Mapping"),
                            ("session_timeout", "Session Timeout"),
                            ("configuration_change", "Configuration Change"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=50)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "sso_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sso.ssoprovider",
                    ),
                ),
                (
                    "sso_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sso.ssosession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SAMLProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idp_sso_url", models.URLField(help_text="IdP Single Sign-On URL")),
                (
                    "idp_sls_url",
                    models.URLField(
                        blank=True, help_text="IdP Single Logout Service URL (optional)"
                    ),
                ),
                (
                    "idp_x509_cert",
                    models.TextField(help_text="IdP X.509 Certificate (Base64 encoded)"),
                ),
                ("sp_entity_id", models.CharField(blank=True, max_length=500)),
                (
                    "sp_acs_url",
                    models.URLField(blank=True, help_text="Assertion Consumer Service URL"),
                ),
                ("sp_sls_url", models.URLField(blank=True, help_text="Single Logout Service URL")),
                ("want_assertions_signed", models.BooleanField(default=True)),
                ("want_name_id_encrypted", models.BooleanField(default=False)),
                ("authn_requests_signed", models.BooleanField(default=False)),
                ("logout_requests_signed", models.BooleanField(default=False)),
                (
                    "signature_algorithm",
                    models.CharField(
                        choices=[
                            ("RSA_SHA256", "RSA-SHA256"),
                            ("RSA_SHA1", "RSA-SHA1"),
                            ("DSA_SHA1", "DSA-SHA1"),
                        ],
                        default="RSA_SHA256",
                        max_length=20,
                    ),
                ),
                (
                    "digest_algorithm",
                    models.CharField(
                        choices=[("SHA256", "SHA256"), ("SHA1", "SHA1")],
                        default="SHA256",
                        max_length=10,
                    ),
                ),
                (
                    "sp_x509_cert",
                    models.TextField(
                        blank=True, help_text="SP X.509 Certificate for signing (optional)"
                    ),
                ),
                (
                    "sp_private_key",
                    models.TextField(blank=True, help_text="SP Private Key for signing (optional)"),
                ),
                (
                    "sso_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saml_config",
                        to="sso.ssoprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authorization_url", models.URLField(help_text="Authorization endpoint URL")),
                ("token_url", models.URLField(help_text="Token endpoint URL")),
                (
                    "userinfo_url",
                    models.URLField(
                        blank=True, help_text="UserInfo endpoint URL (for OpenID Connect)"
                    ),
                ),
                (
                    "jwks_url",
                    models.URLField(
                        blank=True, help_text="JSON Web Key Set URL (for OpenID Connect)"
                    ),
                ),
                (
                    "discovery_url",
                    models.URLField(
                        blank=True, help_text="OpenID Connect Discovery URL (optional)"
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=500)),
                (
                    "grant_type",
                    models.CharField(
                        choices=[
                            ("authorization_code", "Authorization Code"),
                            ("implicit", "Implicit"),
                            ("client_credentials", "Client Credentials"),
                        ],
                        default="authorization_code",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="openid profile email",
                        help_text="Space-separated OAuth scopes",
                        max_length=500,
                    ),
                ),
                (
                    "use_oidc",
                    models.BooleanField(default=True, help_text="Use OpenID Connect features"),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                (
                    "sso_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_config",
                        to="sso.ssoprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sso_attribute",
                    models.CharField(help_text="Attribute name from SSO provider", max_length=100),
                ),
                (
                    "user_field",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("first_name", "First Name"),
                            ("last_name", "Last Name"),
                            ("username", "Username"),
                            ("is_staff", "Staff Status"),
                            ("is_superuser", "Superuser Status"),
                            ("groups", "Groups"),
                        ],
                        help_text="User model field to map to",
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "default_value",
                    models.CharField(
                        blank=True,
                        help_text="Default value if attribute not provided",
                        max_length=255,
                    ),
                ),
                (
                    "transform_expression",
                    models.TextField(
                        blank=True, help_text="Python expression to transform attribute value"
                    ),
                ),
                (
                    "sso_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mappings",
                        to="sso.ssoprovider",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ssosession",
            index=models.Index(fields=["user", "status"], name="sso_ssosess_user_id_337eff_idx"),
        ),
        migrations.AddIndex(
            model_name="ssosession",
            index=models.Index(
                fields=["sso_provider", "status"], name="sso_ssosess_sso_pro_5352df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ssosession",
            index=models.Index(fields=["created_at"], name="sso_ssosess_created_d4e459_idx"),
        ),
        migrations.AddIndex(
            model_name="ssoprovider",
            index=models.Index(
                fields=["tenant", "is_active"], name="sso_ssoprov_tenant__52e67f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ssoprovider",
            index=models.Index(
                fields=["tenant", "is_primary"], name="sso_ssoprov_tenant__2c888d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ssoprovider",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="ssoauditlog",
            index=models.Index(fields=["event_timestamp"], name="sso_ssoaudi_event_t_61d84d_idx"),
        ),
        migrations.AddIndex(
            model_name="ssoauditlog",
            index=models.Index(
                fields=["sso_provider", "event_type"], name="sso_ssoaudi_sso_pro_dbaa39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ssoauditlog",
            index=models.Index(
                fields=["user", "event_type"], name="sso_ssoaudi_user_id_b40f58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ssoauditlog",
            index=models.Index(
                fields=["success", "event_timestamp"], name="sso_ssoaudi_success_072ff2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attributemapping",
            unique_together={("sso_provider", "sso_attribute")},
        ),
    ]
