# Generated by Codex on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssoprovider",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_providers",
                to="core.tenant",
            ),
        ),
    ]
